
name = "cloudflare-ai-image"
main = "index.js"
compatibility_date = "2023-09-01"
[[kv_namespaces]]
binding = "IMAGE_KV"
id = "3b5ff07648714d70aae459de17f032f3"

[vars]
url="https://cloudflare-ai-image.2winter-dev.workers.dev"
account_id = "1b30cdc6287a5cfbbd6d1a2d832f18c8"
SF_TOKEN = "9A8JxqcNuNLHPZgaSPhO7z0-QZnjhxtMSvuiItNj"
CF_IMG2TEXT_MODEL = "@cf/bytedance/stable-diffusion-xl-lightning"
FLUX_NUM_STEPS = 10

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
